from app.core.bp_client import BackpackTFClient
from app.models.enums import Intent
from app.models.listings import BPListing, CurrencyValue, SnapshotBPListing

"""Generated by AI and reviewed. Not written by hand."""


class FakeBP(BackpackTFClient):
    def __init__(self, snapshots=None):
        self.api_key = "k"
        self.token = "t"
        self.snapshots: dict[str, list[SnapshotBPListing]] = snapshots or {}
        self.pages: list[tuple[list[BPListing], dict | None]] = []
        self.calls = 0
        self.patched: list[tuple[str, float | None, float | None]] = []
        self.patched_listing: BPListing | None = None

    async def get_snapshot(self, sku, intent=None, raw=False):
        return self.snapshots.get(sku, [])

    async def get_listings(self, intent=None, raw=False, limit=1000, skip=0):
        self.calls += 1
        return self.pages.pop(0)

    async def patch_listing_price(self, listing_id, keys, metal):
        self.patched.append((listing_id, keys, metal))
        assert self.patched_listing is not None
        return self.patched_listing


def bp_listing_dict(id="L1", keys=5, metal=0.0):
    return {
        "id": id,
        "steamid": "s",
        "intent": "buy",
        "count": 1,
        "status": "active",
        "currencies": {"keys": keys, "metal": metal},
        "item": {
            "defindex": 5021,
            "name": "Key",
            "baseName": "Key",
            "quality": {"name": "Unique", "id": 6},
            "spells": [],
        },
        "listedAt": 1,
    }


def snap(steamid, keys, metal=0.0, intent=Intent.buy, spelled=False):
    return SnapshotBPListing(
        steamid=steamid,
        intent=intent,
        currencies=CurrencyValue(keys=keys, metal=metal),
        is_spelled=spelled,
        item_name="x",
    )
