"""Tests generated by AI and reviewed. Not written by hand."""

import pytest

from app.db import models
from app.models.enums import SortDirection
from app.services.listing_service import sort_order_states


def buy_state(listing_id, keys, metal=0.0):
    return models.BuyorderState(
        listing_id=listing_id,
        steamid="s",
        item_name="Key",
        user_keys=keys,
        user_metal=metal,
    )


def sell_state(listing_id, keys, metal=0.0):
    return models.SellorderState(
        listing_id=listing_id,
        steamid="s",
        item_name="Key",
        user_keys=keys,
        user_metal=metal,
    )


def ids(states):
    return [s.listing_id for s in states]


def test_none_sort_preserves_order():
    states = [buy_state("L1", 10), buy_state("L2", 5)]
    assert ids(sort_order_states(states, None)) == ["L1", "L2"]


@pytest.mark.parametrize(
    "sort, expected",
    [(SortDirection.asc, ["L2", "L3", "L1"]), (SortDirection.desc, ["L1", "L3", "L2"])],
)
def test_sorts_by_keys(sort, expected):
    states = [buy_state("L1", 10), buy_state("L2", 5), buy_state("L3", 7)]
    assert ids(sort_order_states(states, sort)) == expected


@pytest.mark.parametrize(
    "sort, expected",
    [(SortDirection.asc, ["L1", "L2"]), (SortDirection.desc, ["L2", "L1"])],
)
def test_keys_tie_breaks_on_metal(sort, expected):
    states = [buy_state("L1", 5, metal=1.0), buy_state("L2", 5, metal=9.0)]
    assert ids(sort_order_states(states, sort)) == expected


def test_none_keys_treated_as_zero():
    states = [buy_state("L1", 10), buy_state("L2", None)]
    assert ids(sort_order_states(states, SortDirection.asc)) == ["L2", "L1"]


def test_does_not_mutate_input():
    states = [buy_state("L1", 10), buy_state("L2", 5)]
    result = sort_order_states(states, SortDirection.asc)
    assert ids(states) == ["L1", "L2"]
    assert result is not states


def test_sorts_sellorder_states():
    states = [sell_state("L1", 3), sell_state("L2", 8)]
    assert ids(sort_order_states(states, SortDirection.desc)) == ["L2", "L1"]


def test_empty_input():
    assert sort_order_states([], SortDirection.asc) == []
