from app import crud
from app.core.bp_client import BackpackTFError
from app.core.scanner import Scanner
from app.core.sync_tracker import buy_sync_tracker
from app.db import models
from app.models.enums import Intent
from app.models.listings import BPListing, CurrencyValue, SnapshotBPListing
from app.services import scanner_service
from tests.fake_bp import FakeBP, bp_listing_dict

"""Tests generated by AI and reviewed. Not written by hand."""

USER = "76561198061440669"


class RaisingBP(FakeBP):
    async def get_snapshot(self, sku, intent=None, raw=False):
        raise BackpackTFError("boom")


def snap(steamid, keys, metal=0.0, intent=Intent.buy, spelled=False):
    return SnapshotBPListing(
        steamid=steamid,
        intent=intent,
        currencies=CurrencyValue(keys=keys, metal=metal),
        is_spelled=spelled,
        item_name="x",
    )


async def seed_listing(db_session, listing_id="L1", intent=Intent.buy):
    item = models.Item(defindex=5021, name="Key", quality="Unique", particle=None)
    db_session.add(item)
    await db_session.flush()
    listing = models.Listing(
        id=listing_id,
        steamid="s",
        intent=intent,
        status="active",
        keys=5,
        metal=0.0,
        item_id=item.id,
        item_url="u",
    )
    db_session.add(listing)
    await db_session.commit()
    return listing, item


async def test_update_order_data_new_buyorder(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 5),
                snap("comp", 10),
                snap("seller", 2, intent=Intent.sell),
            ],
        }
    )
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert status == "new"
    assert isinstance(state, models.BuyorderState)
    assert state.user_keys == 5
    assert state.is_outbid is True
    assert state.top_competitor_keys == 10
    assert state.outbid_by == "comp"
    assert state.lowest_seller_keys == 2


async def test_update_order_data_new_sellorder(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.sell)
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 8, intent=Intent.sell),
                snap("comp", 6, intent=Intent.sell),
                snap("buyer", 12, intent=Intent.buy),
            ],
        }
    )
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert status == "new"
    assert isinstance(state, models.SellorderState)
    assert state.user_keys == 8
    assert state.is_undercut is True
    assert state.lowest_competitor_keys == 6
    assert state.undercut_by == "comp"
    assert state.highest_buyer_keys == 12


async def test_update_order_data_buy_no_competitor(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    bp = FakeBP(snapshots={"Key": [snap(USER, 5)]})
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert status == "new"
    assert isinstance(state, models.BuyorderState)
    assert state.is_outbid is False
    assert state.top_competitor_keys is None
    assert state.lowest_seller_keys is None


async def test_update_order_data_unchanged(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    db_session.add(
        models.BuyorderState(
            listing_id=listing.id,
            steamid="s",
            item_name="Key",
            user_keys=5,
            user_metal=0.0,
            top_competitor_keys=10,
            top_competitor_metal=0.0,
            is_outbid=True,
            lowest_seller_keys=2,
            lowest_seller_metal=0.0,
        )
    )
    await db_session.commit()
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 5),
                snap("comp", 10),
                snap("seller", 2, intent=Intent.sell),
            ],
        }
    )
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert status == "unchanged"
    assert len(await crud.get_stored_buyorder_state_histories(db_session)) == 0


async def test_update_order_data_updated_writes_history(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    db_session.add(
        models.BuyorderState(
            listing_id=listing.id,
            steamid="s",
            item_name="Key",
            user_keys=5,
            user_metal=0.0,
            top_competitor_keys=10,
            top_competitor_metal=0.0,
            is_outbid=True,
            lowest_seller_keys=2,
            lowest_seller_metal=0.0,
        )
    )
    await db_session.commit()
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 6),
                snap("comp", 10),
                snap("seller", 2, intent=Intent.sell),
            ],
        }
    )
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert status == "updated"
    assert isinstance(state, models.BuyorderState)
    assert state.user_keys == 6
    assert len(await crud.get_stored_buyorder_state_histories(db_session)) == 1


async def test_update_order_data_skipped_on_fetch_error(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=RaisingBP()), listing
    )
    assert state is None and status == "skipped"


async def test_update_order_data_inactive_when_users_order_missing(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    bp = FakeBP(snapshots={"Key": [snap("comp", 10)]})
    state, status = await scanner_service.update_order_data(
        db_session, Scanner(bp=bp), listing
    )
    assert state is None and status == "skipped"
    assert listing.status == "inactive"


async def test_refresh_order_states_updates_tracker(db_session, monkeypatch):
    async def no_sleep(_):
        return None

    monkeypatch.setattr(scanner_service.asyncio, "sleep", no_sleep)
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 5),
                snap("comp", 10),
                snap("seller", 2, intent=Intent.sell),
            ],
        }
    )
    await scanner_service.refresh_order_states(
        db_session, Scanner(bp=bp), buy_sync_tracker, Intent.buy
    )
    assert buy_sync_tracker.total == 1
    assert buy_sync_tracker.current == 1
    assert buy_sync_tracker.synced_ids == [listing.id]


async def test_sync_and_scan_orders_end_to_end(db_session, monkeypatch):
    async def no_sleep(_):
        return None

    monkeypatch.setattr(scanner_service.asyncio, "sleep", no_sleep)
    bp = FakeBP(
        snapshots={
            "Key": [
                snap(USER, 5),
                snap("comp", 10),
                snap("seller", 2, intent=Intent.sell),
            ],
        }
    )
    bp.pages = [([BPListing.from_api(bp_listing_dict())], None)]
    await scanner_service.sync_and_scan_orders(
        db_session, bp, Scanner(bp=bp), buy_sync_tracker, Intent.buy
    )
    assert buy_sync_tracker.synced_ids == ["L1"]
    stored = await crud.get_stored_listings(db_session)
    assert len(stored) == 1
    assert len(await crud.get_stored_buyorder_state_histories(db_session)) == 0
