import pytest

from app import crud
from app.db import models
from app.models.enums import Intent, RoundingMethod
from app.models.listings import BPListing, CurrencyValue
from app.services import listing_service
from tests.fake_bp import FakeBP, bp_listing_dict

"""Tests generated by AI and reviewed. Not written by hand."""


async def seed_listing(
    db_session, listing_id="L1", intent=Intent.buy, keys=5, metal=0.0
):
    item = models.Item(defindex=5021, name="Key", quality="Unique", particle=None)
    db_session.add(item)
    await db_session.flush()
    listing = models.Listing(
        id=listing_id,
        steamid="s",
        intent=intent,
        status="active",
        keys=keys,
        metal=metal,
        item_id=item.id,
        item_url="u",
    )
    db_session.add(listing)
    await db_session.commit()
    return listing, item


async def seed_buyorder_state(db_session, listing, top_competitor_keys=10, user_keys=5):
    state = models.BuyorderState(
        listing_id=listing.id,
        steamid="s",
        item_name="Key",
        user_keys=user_keys,
        user_metal=0.0,
        top_competitor_keys=top_competitor_keys,
        top_competitor_metal=0.0,
        is_outbid=True,
        lowest_seller_keys=2,
        lowest_seller_metal=0.0,
    )
    db_session.add(state)
    await db_session.commit()
    return state


async def test_sync_listings_single_page(db_session):
    bp = FakeBP()
    bp.pages = [([BPListing.from_api(bp_listing_dict())], None)]
    synced = await listing_service.sync_listings(db_session, bp)
    assert len(synced) == 1
    assert bp.calls == 1
    stored = await crud.get_stored_listings(db_session)
    assert len(stored) == 1
    assert stored[0].item.name == "Key"


async def test_sync_listings_first_page_only(db_session):
    bp = FakeBP()
    bp.pages = [
        ([BPListing.from_api(bp_listing_dict())], {"total": 1500}),
        ([BPListing.from_api(bp_listing_dict(id="L2"))], None),
    ]
    synced = await listing_service.sync_listings(db_session, bp)
    assert len(synced) == 1
    assert bp.calls == 1


async def test_sync_listings_sync_all_drains_pages(db_session):
    bp = FakeBP()
    bp.pages = [
        (
            [
                BPListing.from_api(bp_listing_dict()),
                BPListing.from_api(bp_listing_dict(id="L2")),
            ],
            {"total": 1500},
        ),
        ([BPListing.from_api(bp_listing_dict(id="L3"))], None),
    ]
    synced = await listing_service.sync_listings(db_session, bp, sync_all=True)
    assert len(synced) == 3
    assert bp.calls == 2
    assert len(await crud.get_stored_listings(db_session)) == 3


class RaisingFakeBP(FakeBP):
    def __init__(self):
        super().__init__()
        self.pages = [([BPListing.from_api(bp_listing_dict())], {"total": 1500})]

    async def get_listings(self, intent=None, raw=False, limit=1000, skip=0):
        self.calls += 1
        if self.calls > 1:
            raise RuntimeError("boom")
        return self.pages.pop(0)


async def test_sync_listings_rolls_back_on_error(db_session):
    with pytest.raises(RuntimeError):
        await listing_service.sync_listings(db_session, RaisingFakeBP(), sync_all=True)
    assert len(await crud.get_stored_listings(db_session)) == 0


async def test_get_competitor_price_buy(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    await seed_buyorder_state(db_session, listing)
    price = await listing_service.get_competitor_price(
        db_session, listing.id, Intent.buy
    )
    assert price == CurrencyValue(keys=10, metal=0)


async def test_get_competitor_price_sell(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.sell)
    state = models.SellorderState(
        listing_id=listing.id,
        steamid="s",
        item_name="Key",
        user_keys=5,
        user_metal=0.0,
        lowest_competitor_keys=3,
        lowest_competitor_metal=2.0,
        is_undercut=True,
        highest_buyer_keys=2,
        highest_buyer_metal=0.0,
    )
    db_session.add(state)
    await db_session.commit()
    price = await listing_service.get_competitor_price(
        db_session, listing.id, Intent.sell
    )
    assert price == CurrencyValue(keys=3, metal=2)


async def test_get_competitor_price_missing(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    assert (
        await listing_service.get_competitor_price(db_session, listing.id, Intent.buy)
        is None
    )


async def test_update_listing_price_buy_up_1_key(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    await seed_buyorder_state(db_session, listing, top_competitor_keys=10)
    bp = FakeBP()
    bp.patched_listing = BPListing.from_api(
        bp_listing_dict(id=listing.id, keys=11, metal=0.0)
    )
    updated = await listing_service.update_listing_price(
        db_session, listing, RoundingMethod.UP_1_KEY, bp
    )
    assert bp.patched == [(listing.id, 11.0, 0.0)]
    assert updated is not None and updated.keys == 11


async def test_update_listing_price_no_competitor(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    bp = FakeBP()
    assert (
        await listing_service.update_listing_price(
            db_session, listing, RoundingMethod.UP_1_KEY, bp
        )
        is None
    )
    assert bp.patched == []


async def test_update_listing_price_down_1_key_zero(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    await seed_buyorder_state(db_session, listing, top_competitor_keys=0, user_keys=0)
    bp = FakeBP()
    assert (
        await listing_service.update_listing_price(
            db_session, listing, RoundingMethod.DOWN_1_KEY, bp
        )
        is None
    )
    assert bp.patched == []


async def test_update_order_price_updates_state_and_history(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy, keys=11)
    await seed_buyorder_state(db_session, listing, top_competitor_keys=10, user_keys=5)
    state = await listing_service.update_order_price(db_session, listing)
    assert state is not None and state.user_keys == 11
    assert isinstance(state, models.BuyorderState)
    assert state.is_outbid is False  # 11 >= 10 clears outbid
    assert len(await crud.get_stored_buyorder_state_histories(db_session)) == 1


async def test_update_order_price_unchanged_no_history(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy, keys=5)
    await seed_buyorder_state(db_session, listing, top_competitor_keys=10, user_keys=5)
    state = await listing_service.update_order_price(db_session, listing)
    assert state is not None
    assert len(await crud.get_stored_buyorder_state_histories(db_session)) == 0


async def test_update_order_price_no_state(db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.buy)
    assert await listing_service.update_order_price(db_session, listing) is None
