"""Generated by AI and reviewed. Not written by hand."""

from app.models.enums import Intent
from tests.seed_helpers import seed_buyorder_state, seed_listing, seed_sellorder_state


async def test_dashboard_renders(client):
    resp = await client.get("/")
    assert resp.status_code == 200
    assert "Only Beaten" in resp.text


async def test_buyorders_alias_renders(client):
    resp = await client.get("/buyorders")
    assert resp.status_code == 200
    assert "Only Beaten" in resp.text


async def test_dashboard_shows_seeded_buyorder(client, db_session):
    listing, _ = await seed_listing(db_session, listing_id="L1")
    await seed_buyorder_state(db_session, listing)
    resp = await client.get("/")
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "Key" in resp.text


async def test_dashboard_only_beaten_filter(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1")
    l2, _ = await seed_listing(db_session, listing_id="L2")
    await seed_buyorder_state(db_session, l1, is_outbid=True)
    await seed_buyorder_state(db_session, l2, is_outbid=False)
    resp = await client.get("/", params={"only_beaten": "True"})
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "id=row-L2" not in resp.text


async def test_sellorders_dashboard_renders(client):
    resp = await client.get("/sellorders")
    assert resp.status_code == 200
    assert "Lowest competitor" in resp.text


async def test_sellorders_shows_seeded(client, db_session):
    listing, _ = await seed_listing(db_session, listing_id="L1", intent=Intent.sell)
    await seed_sellorder_state(db_session, listing)
    resp = await client.get("/sellorders")
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "Key" in resp.text


async def test_sellorders_only_beaten_filter(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1", intent=Intent.sell)
    l2, _ = await seed_listing(db_session, listing_id="L2", intent=Intent.sell)
    await seed_sellorder_state(db_session, l1, is_undercut=True)
    await seed_sellorder_state(db_session, l2, is_undercut=False)
    resp = await client.get("/sellorders", params={"only_beaten": "True"})
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "id=row-L2" not in resp.text


async def test_buyorders_history_renders(client):
    resp = await client.get("/buyorders-history")
    assert resp.status_code == 200
    assert "Regained top" in resp.text


async def test_sellorders_history_renders(client):
    resp = await client.get("/sellorders-history")
    assert resp.status_code == 200
    assert "Regained lowest" in resp.text


async def test_sync_status_buy(client):
    resp = await client.get("/sync-status/buy")
    assert resp.status_code == 200
    assert "sync-area" in resp.text


async def test_sync_status_sell(client):
    resp = await client.get("/sync-status/sell")
    assert resp.status_code == 200
    assert "sync-area" in resp.text


async def test_round_price_missing_listing_404(client):
    resp = await client.patch("/listings/does-not-exist/round-price")
    assert resp.status_code == 404
