"""Generated by AI and reviewed. Not written by hand."""

import re

import pytest

from app.models.enums import Intent
from tests.seed_helpers import seed_buyorder_state, seed_listing, seed_sellorder_state


def row_order(html: str) -> list[str]:
    return re.findall(r'id=row-([^\s"]+)', html)


async def seed_priced_buyorders(db_session, prices):
    for listing_id, keys in prices.items():
        listing, _ = await seed_listing(db_session, listing_id=listing_id)
        await seed_buyorder_state(db_session, listing, user_keys=keys)


async def test_dashboard_renders(client):
    resp = await client.get("/")
    assert resp.status_code == 200
    assert "Only Beaten" in resp.text


async def test_buyorders_alias_renders(client):
    resp = await client.get("/buyorders")
    assert resp.status_code == 200
    assert "Only Beaten" in resp.text


async def test_dashboard_shows_seeded_buyorder(client, db_session):
    listing, _ = await seed_listing(db_session, listing_id="L1")
    await seed_buyorder_state(db_session, listing)
    resp = await client.get("/")
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "Key" in resp.text


async def test_dashboard_only_beaten_filter(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1")
    l2, _ = await seed_listing(db_session, listing_id="L2")
    await seed_buyorder_state(db_session, l1, is_outbid=True)
    await seed_buyorder_state(db_session, l2, is_outbid=False)
    resp = await client.get("/", params={"only_beaten": "True"})
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "id=row-L2" not in resp.text


async def test_dashboard_without_sort_renders_all_rows(client, db_session):
    await seed_priced_buyorders(db_session, {"L1": 10, "L2": 5, "L3": 7})
    resp = await client.get("/")
    assert set(row_order(resp.text)) == {"L1", "L2", "L3"}


async def test_dashboard_sort_asc(client, db_session):
    await seed_priced_buyorders(db_session, {"L1": 10, "L2": 5, "L3": 7})
    resp = await client.get("/", params={"sort": "asc"})
    assert row_order(resp.text) == ["L2", "L3", "L1"]


async def test_dashboard_sort_desc(client, db_session):
    await seed_priced_buyorders(db_session, {"L1": 10, "L2": 5, "L3": 7})
    resp = await client.get("/", params={"sort": "desc"})
    assert row_order(resp.text) == ["L1", "L3", "L2"]


async def test_dashboard_sort_tolerates_null_keys(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1")
    l2, _ = await seed_listing(db_session, listing_id="L2")
    await seed_buyorder_state(db_session, l1, user_keys=10)
    await seed_buyorder_state(db_session, l2, user_keys=None)
    resp = await client.get("/", params={"sort": "desc"})
    assert resp.status_code == 200
    assert row_order(resp.text) == ["L1", "L2"]


async def test_dashboard_sort_invalid_value_rejected(client):
    assert (await client.get("/", params={"sort": "sideways"})).status_code == 422


async def test_dashboard_sort_by_invalid_value_rejected(client):
    assert (await client.get("/", params={"sort_by": "sideways"})).status_code == 422


@pytest.mark.parametrize(
    "sort, expected", [("asc", ["L2", "L3", "L1"]), ("desc", ["L1", "L3", "L2"])]
)
async def test_dashboard_sort_by_lowest_seller(client, db_session, sort, expected):
    for listing_id, seller_keys in {"L1": 7, "L2": 3, "L3": 5}.items():
        listing, _ = await seed_listing(db_session, listing_id=listing_id)
        await seed_buyorder_state(db_session, listing, lowest_seller_keys=seller_keys)
    resp = await client.get("/", params={"sort": sort, "sort_by": "lowest_seller"})
    assert row_order(resp.text) == expected


@pytest.mark.parametrize(
    "sort, expected", [("asc", ["S2", "S3", "S1"]), ("desc", ["S1", "S3", "S2"])]
)
async def test_sellorders_sort_by_highest_buyer(client, db_session, sort, expected):
    for listing_id, buyer_keys in {"S1": 7, "S2": 3, "S3": 5}.items():
        listing, _ = await seed_listing(
            db_session, listing_id=listing_id, intent=Intent.sell
        )
        await seed_sellorder_state(db_session, listing, highest_buyer_keys=buyer_keys)
    resp = await client.get(
        "/sellorders", params={"sort": sort, "sort_by": "highest_buyer"}
    )
    assert row_order(resp.text) == expected


async def test_dashboard_headers_match_buy_intent(client):
    resp = await client.get("/")
    assert resp.status_code == 200
    assert "Top Competitor" in resp.text
    assert "Lowest Seller" in resp.text
    assert "Highest Buyer" not in resp.text


async def test_sellorders_headers_match_sell_intent(client):
    resp = await client.get("/sellorders")
    assert resp.status_code == 200
    assert "Lowest Competitor" in resp.text
    assert "Highest Buyer" in resp.text
    assert "Lowest Seller" not in resp.text


@pytest.mark.parametrize(
    "sort, next_direction, arrow",
    [
        (None, "desc", None),
        ("asc", "desc", "&#9650;"),
        ("desc", "asc", "&#9660;"),
    ],
)
async def test_dashboard_sort_header_and_arrow(client, sort, next_direction, arrow):
    resp = await client.get("/", params={"sort": sort} if sort else {})
    assert f'href="/?sort={next_direction}' in resp.text
    if arrow:
        assert arrow in resp.text
    else:
        assert "&#9650;" not in resp.text
        assert "&#9660;" not in resp.text


async def test_only_beaten_toggle_preserves_sort(client):
    resp = await client.get("/", params={"sort": "desc", "sort_by": "competitor"})
    assert 'hx-get="/?sort=desc&amp;sort_by=competitor"' in resp.text


async def test_sort_header_preserves_only_beaten(client):
    resp = await client.get("/", params={"sort": "desc", "only_beaten": "True"})
    assert 'href="/?sort=asc&amp;sort_by=owner&amp;only_beaten=True' in resp.text


async def test_sellorders_dashboard_renders(client):
    resp = await client.get("/sellorders")
    assert resp.status_code == 200
    assert "Lowest Competitor" in resp.text


async def test_sellorders_shows_seeded(client, db_session):
    listing, _ = await seed_listing(db_session, listing_id="L1", intent=Intent.sell)
    await seed_sellorder_state(db_session, listing)
    resp = await client.get("/sellorders")
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "Key" in resp.text


async def test_sellorders_only_beaten_filter(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1", intent=Intent.sell)
    l2, _ = await seed_listing(db_session, listing_id="L2", intent=Intent.sell)
    await seed_sellorder_state(db_session, l1, is_undercut=True)
    await seed_sellorder_state(db_session, l2, is_undercut=False)
    resp = await client.get("/sellorders", params={"only_beaten": "True"})
    assert resp.status_code == 200
    assert "id=row-L1" in resp.text
    assert "id=row-L2" not in resp.text


async def test_sellorders_sort_desc(client, db_session):
    for listing_id, keys in {"S1": 3, "S2": 8, "S3": 5}.items():
        listing, _ = await seed_listing(
            db_session, listing_id=listing_id, intent=Intent.sell
        )
        await seed_sellorder_state(db_session, listing, user_keys=keys)
    resp = await client.get("/sellorders", params={"sort": "desc"})
    assert row_order(resp.text) == ["S2", "S3", "S1"]


async def test_sellorders_only_beaten_toggle_preserves_sort(client):
    resp = await client.get(
        "/sellorders", params={"sort": "asc", "sort_by": "highest_buyer"}
    )
    assert 'hx-get="/sellorders?sort=asc&amp;sort_by=highest_buyer"' in resp.text


async def test_round_price_missing_listing_404(client):
    resp = await client.patch("/listings/does-not-exist/round-price")
    assert resp.status_code == 404


async def test_buyorders_history_renders(client):
    resp = await client.get("/buyorders-history")
    assert resp.status_code == 200
    assert "Regained top" in resp.text


async def test_sellorders_history_renders(client):
    resp = await client.get("/sellorders-history")
    assert resp.status_code == 200
    assert "Regained lowest" in resp.text


async def test_sync_status_buy(client):
    resp = await client.get("/sync-status/buy")
    assert resp.status_code == 200
    assert "sync-area" in resp.text


async def test_sync_status_sell(client):
    resp = await client.get("/sync-status/sell")
    assert resp.status_code == 200
    assert "sync-area" in resp.text
