"""Generated by AI and reviewed. Not written by hand."""

from app.db import models
from app.models.enums import Intent
from tests.seed_helpers import seed_buyorder_state, seed_listing, seed_sellorder_state


async def test_listings_empty(client):
    resp = await client.get("/api/listings")
    assert resp.status_code == 200
    assert resp.json() == []


async def test_listings_returns_seeded(client, db_session):
    await seed_listing(db_session)
    resp = await client.get("/api/listings")
    assert resp.status_code == 200
    body = resp.json()
    assert len(body) == 1
    assert body[0]["id"] == "L1"
    assert body[0]["intent"] == "buy"
    assert body[0]["item"]["name"] == "Key"


async def test_listings_intent_filter(client, db_session):
    await seed_listing(db_session, listing_id="L1", intent=Intent.buy)
    await seed_listing(db_session, listing_id="L2", intent=Intent.sell)
    resp = await client.get("/api/listings", params={"intent": "sell"})
    assert resp.status_code == 200
    assert [item["id"] for item in resp.json()] == ["L2"]


async def test_get_listing_by_id(client, db_session):
    await seed_listing(db_session)
    resp = await client.get("/api/listings/L1")
    assert resp.status_code == 200
    assert resp.json()["id"] == "L1"


async def test_get_listing_by_id_not_found(client):
    resp = await client.get("/api/listings/does-not-exist")
    assert resp.status_code == 404


async def test_buyorder_states(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1")
    l2, _ = await seed_listing(db_session, listing_id="L2")
    await seed_buyorder_state(db_session, l1, is_outbid=True)
    await seed_buyorder_state(db_session, l2, is_outbid=False)
    resp = await client.get("/api/buyorder_states")
    assert resp.status_code == 200
    assert len(resp.json()) == 2
    resp = await client.get("/api/buyorder_states", params={"only_beaten": "true"})
    assert len(resp.json()) == 1
    assert resp.json()[0]["is_outbid"] is True


async def test_total_buyorders_outbid(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1")
    l2, _ = await seed_listing(db_session, listing_id="L2")
    await seed_buyorder_state(db_session, l1, is_outbid=True)
    await seed_buyorder_state(db_session, l2, is_outbid=False)
    resp = await client.get("/api/buyorder_states/total_buyorders_outbid")
    assert resp.status_code == 200
    assert resp.json() == 1


async def test_buyorder_state_histories(client, db_session):
    listing, _ = await seed_listing(db_session)
    db_session.add(
        models.BuyorderStateHistory(
            listing_id=listing.id,
            old_user_keys=5,
            old_user_metal=0.0,
            old_top_competitor_keys=10,
            old_top_competitor_metal=0.0,
            old_is_outbid=True,
            old_lowest_seller_keys=2,
            old_lowest_seller_metal=0.0,
            new_user_keys=6,
            new_user_metal=0.0,
            new_top_competitor_keys=10,
            new_top_competitor_metal=0.0,
            new_is_outbid=True,
            new_lowest_seller_keys=2,
            new_lowest_seller_metal=0.0,
            outbid_changed=True,
        )
    )
    await db_session.commit()
    resp = await client.get("/api/buyorder_state_histories")
    assert resp.status_code == 200
    body = resp.json()
    assert len(body) == 1
    assert body[0]["outbid_changed"] is True
    assert body[0]["listing"]["item"]["name"] == "Key"


async def test_sellorder_states(client, db_session):
    l1, _ = await seed_listing(db_session, listing_id="L1", intent=Intent.sell)
    l2, _ = await seed_listing(db_session, listing_id="L2", intent=Intent.sell)
    await seed_sellorder_state(db_session, l1, is_undercut=True)
    await seed_sellorder_state(db_session, l2, is_undercut=False)
    resp = await client.get("/api/sellorder_states")
    assert resp.status_code == 200
    assert len(resp.json()) == 2
    resp = await client.get("/api/sellorder_states", params={"only_beaten": "true"})
    assert len(resp.json()) == 1
    assert resp.json()[0]["is_undercut"] is True


async def test_refresh_buyorder_state_not_found(client):
    resp = await client.post("/api/buyorder_states/does-not-exist/refresh")
    assert resp.status_code == 404


async def test_refresh_buyorder_state_rejects_sell_listing(client, db_session):
    listing, _ = await seed_listing(db_session, intent=Intent.sell)
    resp = await client.post(f"/api/buyorder_states/{listing.id}/refresh")
    assert resp.status_code == 400
