"""Generated by AI and reviewed. Not written by hand."""

import json
from typing import cast

import httpx
import pytest

from app.core.bp_client import BackpackTFClient, BackpackTFError, RateLimitedError
from app.models.listings import SnapshotBPListing


def make_client(handler):
    client = BackpackTFClient("key", "token")
    client.client = httpx.AsyncClient(
        transport=httpx.MockTransport(handler), base_url="https://backpack.tf/api"
    )

    return client


def listing_dict(id="L1", intent="buy"):
    return {
        "id": id,
        "steamid": "s",
        "intent": intent,
        "count": 1,
        "status": "active",
        "currencies": {"keys": 5, "metal": 0},
        "details": None,
        "item": {
            "defindex": 5021,
            "name": "Key",
            "baseName": "Key",
            "quality": {"name": "Unique", "id": 6},
            "craftable": 1,
            "spells": [],
        },
        "listedAt": 123,
    }


async def test_get_listings_parses():
    def handler(request):
        assert request.url.path.endswith("/v2/classifieds/listings")
        return httpx.Response(
            200, json={"listings": [listing_dict()], "cursor": {"page": 2}}
        )

    client = make_client(handler)
    listings, cursor = await client.get_listings()
    assert len(listings) == 1
    assert listings[0].id == "L1"
    assert listings[0].currencies.keys == 5
    assert listings[0].item.name == "Key"
    assert cursor == {"page": 2}


async def test_get_listings_raw():
    def handler(request):
        return httpx.Response(200, json={"listings": [listing_dict()], "cursor": None})

    client = make_client(handler)
    listings, cursor = await client.get_listings(raw=True)
    assert cast(list[dict], listings)[0]["id"] == "L1"
    assert cursor is None


async def test_get_listings_intent_filter():
    def handler(request):
        return httpx.Response(
            200,
            json={
                "listings": [listing_dict("L1", "buy"), listing_dict("L2", "sell")],
                "cursor": None,
            },
        )

    client = make_client(handler)
    listings, _ = await client.get_listings(intent="buy")
    assert [listing.id for listing in listings] == ["L1"]


async def test_get_snapshot_parses():
    def handler(request):
        return httpx.Response(
            200,
            json={
                "listings": [
                    {
                        "steamid": "s",
                        "intent": "buy",
                        "currencies": {"keys": 5, "metal": 0},
                        "details": None,
                        "item": {"attributes": [{"defindex": 1004}]},
                    }
                ],
                "cursor": None,
            },
        )

    client = make_client(handler)
    listings = await client.get_snapshot("sku")
    assert len(listings) == 1
    assert listings[0].item_name == "sku"
    assert listings[0].is_spelled is True


async def test_get_snapshot_detects_no_spell():
    def handler(request):
        return httpx.Response(
            200,
            json={
                "listings": [
                    {
                        "steamid": "s",
                        "intent": "sell",
                        "currencies": {"keys": 5, "metal": 0},
                        "details": None,
                        "item": {"attributes": [{"defindex": 1}]},
                    }
                ],
                "cursor": None,
            },
        )

    client = make_client(handler)
    listings = await client.get_snapshot("sku")
    assert listings[0].is_spelled is False


async def test_patch_listing_price_builds_body_and_parses():
    seen = {}

    def handler(request):
        assert request.url.path.endswith("/v2/classifieds/listings/L1")
        seen["body"] = json.loads(request.content)
        return httpx.Response(200, json=listing_dict())

    client = make_client(handler)
    result = await client.patch_listing_price("L1", 5.5, 1.25)
    assert seen["body"] == {"currencies": {"metal": 1.25, "keys": 5}}
    assert result.id == "L1"


async def test_patch_listing_price_defaults_zero():
    seen = {}

    def handler(request):
        seen["body"] = json.loads(request.content)
        return httpx.Response(200, json=listing_dict())

    client = make_client(handler)
    await client.patch_listing_price("L1", None, None)
    assert seen["body"] == {"currencies": {"metal": 0, "keys": 0}}


async def test_rate_limit_retries_then_succeeds():
    calls = {"n": 0}

    def handler(request):
        calls["n"] += 1
        if calls["n"] == 1:
            return httpx.Response(429, headers={"Retry-After": "0"})
        return httpx.Response(200, json={"listings": [], "cursor": None})

    client = make_client(handler)
    listings, cursor = await client.get_listings()
    assert calls["n"] == 2
    assert listings == []
    assert cursor is None


async def test_rate_limit_exhausted_raises():
    def handler(request):
        return httpx.Response(429, headers={"Retry-After": "0"})

    client = make_client(handler)
    with pytest.raises(RateLimitedError):
        await client.get_listings()


async def test_timeout_raises_backpacktf_error():
    def handler(request):
        raise httpx.ReadTimeout("boom")

    client = make_client(handler)
    with pytest.raises(BackpackTFError, match="Request timed out"):
        await client.get_listings()


async def test_http_error_raises_backpacktf_error():
    def handler(request):
        return httpx.Response(500, json={})

    client = make_client(handler)
    with pytest.raises(BackpackTFError, match="HTTP 500"):
        await client.get_listings()


def test_has_spell():
    assert SnapshotBPListing.has_spell([{"defindex": 1004}]) is True
    assert SnapshotBPListing.has_spell([{"defindex": 1005}]) is True
    assert SnapshotBPListing.has_spell([{"defindex": 1006}]) is True
    assert SnapshotBPListing.has_spell([{"defindex": 1}]) is False
    assert SnapshotBPListing.has_spell([]) is False
